# Device Specific Configuration 
substitutions:
  devicename: soc-gosund-cam-driveway3
  friendlyname: "Socket: Gosung Cam Driveway 3"
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ipaddr: 192.168.49.26
  gateway: !secret gateway
  subnet: !secret subnet
  api_key: !secret api_encryption_key
  ota_password: !secret ota_password

# Common Config
<<: !include includes/base-config.yaml
<<: !include includes/gosund-wp3.yaml


