# Device Specific Configuration 
substitutions:
  devicename: swt-shelly1-garage-door1
  friendlyname: "Switch: Shelly1 Garage Door 1"
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ipaddr: 192.168.49.41
  gateway: !secret gateway
  subnet: !secret subnet
  api_key: !secret api_encryption_key
  ota_password: !secret ota_password

# Common Config
<<: !include includes/base-config.yaml
<<: !include includes/shelly1-garage-door.yaml




    