# Device Specific Configuration 
substitutions:
  devicename: swt-sonoff-pantry-light
  friendlyname: "Switch: Sonoff Pantry Light"
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ipaddr: 192.168.49.34
  gateway: !secret gateway
  subnet: !secret subnet
  api_key: !secret api_encryption_key
  ota_password: !secret ota_password


# Common Config
<<: !include includes/base-config.yaml
<<: !include includes/sonoff-basic.yaml