# Device Specific Configuration 
substitutions:
  devicename: swt-mjsp-breakfast-lights
  friendlyname: "Switch: MJSP Breakfast Area Lights"
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ipaddr: 192.168.49.26
  gateway: !secret gateway
  subnet: !secret subnet
  api_key: !secret api_encryption_key
  ota_password: !secret ota_password

# Common Config
<<: !include includes/base-config.yaml
<<: !include includes/mj-us-ss01.yaml
