esphome:
  name: ${devicename}
  friendly_name: ${friendlyname}

esp8266:
  board: esp01_1m

# button connected to GPIO0
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Button"
    on_press:
      then:
        - switch.toggle: relay
    internal: true

  - platform: template
    name: "Relay State"
    id: relay_state
    
# relay connecected to GPIO12
switch:
  - platform: gpio
    pin: GPIO12
    id: relay
    name: "Relay"
    internal: true
    on_turn_on:
      - switch.turn_on: led
      - binary_sensor.template.publish:
          id: relay_state
          state: ON

    on_turn_off:
      - switch.turn_off: led
      - binary_sensor.template.publish:
          id: relay_state
          state: OFF

  - platform: gpio
    name: "LED"
    id: led
    pin: GPIO13
    inverted: True
    internal: true

  - platform: template
    name: "Switch"
    id: virtual_switch
    turn_on_action:
      - switch.turn_on: relay
    turn_off_action:
      - switch.turn_off: relay

# Sensors with general information.
sensor:
  # Uptime sensor.
  - platform: uptime
    name: Uptime

  # WiFi Signal sensor.
  - platform: wifi_signal
    name: WiFi Signal
    update_interval: 60s